type Point = {
  id: number;
  engAbbr: string;
  ukrName: string;
};

export const BibleData: Point[] = [
  { id: 1, engAbbr: "GEN", ukrName: "Буття" },
  { id: 2, engAbbr: "EXO", ukrName: "Вихід" },
  { id: 3, engAbbr: "LEV", ukrName: "Левит" },
  { id: 4, engAbbr: "NUM", ukrName: "Числа" },
  { id: 5, engAbbr: "DEU", ukrName: "Второзаконня" },
  { id: 6, engAbbr: "JOS", ukrName: "Iсус Навин" },
  { id: 7, engAbbr: "JDG", ukrName: "Судді" },
  { id: 8, engAbbr: "RUT", ukrName: "Рут" },
  { id: 9, engAbbr: "1SA", ukrName: "I Самуїл" },
  { id: 10, engAbbr: "2SA", ukrName: "II Самуїл" },
  { id: 11, engAbbr: "1KI", ukrName: "I Царі" },
  { id: 12, engAbbr: "2KI", ukrName: "II Царі" },
  { id: 13, engAbbr: "1CH", ukrName: "I Хроніка" },
  { id: 14, engAbbr: "2CH", ukrName: "II Хроніка" },
  { id: 15, engAbbr: "EZR", ukrName: "Ездра" },
  { id: 16, engAbbr: "NEH", ukrName: "Неємія" },
  { id: 17, engAbbr: "EST", ukrName: "Естера" },
  { id: 18, engAbbr: "JOB", ukrName: "Іов" },
  { id: 19, engAbbr: "PSA", ukrName: "Псалми" },
  { id: 20, engAbbr: "PRO", ukrName: "Приповідки" },
  { id: 21, engAbbr: "ECC", ukrName: "Проповідник" },
  { id: 22, engAbbr: "SNG", ukrName: "Пісня пісень" },
  { id: 23, engAbbr: "ISA", ukrName: "Ісая" },
  { id: 24, engAbbr: "JER", ukrName: "Єремiя" },
  { id: 25, engAbbr: "LAM", ukrName: "Плач Єремiї" },
  { id: 26, engAbbr: "EZK", ukrName: "Єзекiїль" },
  { id: 27, engAbbr: "DAN", ukrName: "Даниїл" },
  { id: 28, engAbbr: "HOS", ukrName: "Осiя" },
  { id: 29, engAbbr: "JOL", ukrName: "Йоіл" },
  { id: 30, engAbbr: "AMO", ukrName: "Амос" },
  { id: 31, engAbbr: "OBA", ukrName: "Овдiй" },
  { id: 32, engAbbr: "JON", ukrName: "Йона" },
  { id: 33, engAbbr: "MIC", ukrName: "Міхей" },
  { id: 34, engAbbr: "NAM", ukrName: "Наум" },
  { id: 35, engAbbr: "HAB", ukrName: "Авакум" },
  { id: 36, engAbbr: "ZEP", ukrName: "Софонiя" },
  { id: 37, engAbbr: "HAG", ukrName: "Аггей" },
  { id: 38, engAbbr: "ZEC", ukrName: "Захарiя" },
  { id: 39, engAbbr: "MAL", ukrName: "Малахія" },
  { id: 40, engAbbr: "MAT", ukrName: "Матей" },
  { id: 41, engAbbr: "MRK", ukrName: "Марко" },
  { id: 42, engAbbr: "LUK", ukrName: "Лука" },
  { id: 43, engAbbr: "JHN", ukrName: "Йоан" },
  { id: 44, engAbbr: "ACT", ukrName: "Діяння" },
  { id: 45, engAbbr: "ROM", ukrName: "До римлян" },
  { id: 46, engAbbr: "1CO", ukrName: "I до Корінтян" },
  { id: 47, engAbbr: "2CO", ukrName: "II до Корінтян" },
  { id: 48, engAbbr: "GAL", ukrName: "До Галатiв" },
  { id: 49, engAbbr: "EPH", ukrName: "До Ефесян" },
  { id: 50, engAbbr: "PHP", ukrName: "До Филипʼян" },
  { id: 51, engAbbr: "COL", ukrName: "До Колосян" },
  { id: 52, engAbbr: "1TH", ukrName: "I до Солунян" },
  { id: 53, engAbbr: "2TH", ukrName: "II до Солунян" },
  { id: 54, engAbbr: "1TI", ukrName: "I до Тимотея" },
  { id: 55, engAbbr: "2TI", ukrName: "II до Тимотея" },
  { id: 56, engAbbr: "TIT", ukrName: "До Тита" },
  { id: 57, engAbbr: "PHM", ukrName: "До Филимона" },
  { id: 58, engAbbr: "HEB", ukrName: "До євреїв" },
  { id: 59, engAbbr: "JAS", ukrName: "Якова" },
  { id: 60, engAbbr: "1PE", ukrName: "I Послання Петра" },
  { id: 61, engAbbr: "2PE", ukrName: "II Послання Петра" },
  { id: 62, engAbbr: "1JN", ukrName: "I Послання Йоана" },
  { id: 63, engAbbr: "2JN", ukrName: "II Послання Йоана" },
  { id: 64, engAbbr: "3JN", ukrName: "III Послання Йоана" },
  { id: 65, engAbbr: "JUD", ukrName: "Послання Юди" },
  { id: 66, engAbbr: "REV", ukrName: "Обʼявлення" },
];
