type Point = {
  id: number;
  engAbbr: string;
  ukrName: string;
  chaptersNum: number;
};

export const BibleData: Point[] = [
  { id: 1, engAbbr: "GEN", ukrName: "Буття", chaptersNum: 50 },
  { id: 2, engAbbr: "EXO", ukrName: "Вихід", chaptersNum: 40 },
  { id: 3, engAbbr: "LEV", ukrName: "Левит", chaptersNum: 27 },
  { id: 4, engAbbr: "NUM", ukrName: "Числа", chaptersNum: 36 },
  { id: 5, engAbbr: "DEU", ukrName: "Второзаконня", chaptersNum: 34 },
  { id: 6, engAbbr: "JOS", ukrName: "Iсус Навин", chaptersNum: 24 },
  { id: 7, engAbbr: "JDG", ukrName: "Судді", chaptersNum: 21 },
  { id: 8, engAbbr: "RUT", ukrName: "Рут", chaptersNum: 4 },
  { id: 9, engAbbr: "1SA", ukrName: "I Самуїл", chaptersNum: 31 },
  { id: 10, engAbbr: "2SA", ukrName: "II Самуїл", chaptersNum: 24 },
  { id: 11, engAbbr: "1KI", ukrName: "I Царі", chaptersNum: 22 },
  { id: 12, engAbbr: "2KI", ukrName: "II Царі", chaptersNum: 25 },
  { id: 13, engAbbr: "1CH", ukrName: "I Хроніка", chaptersNum: 29 },
  { id: 14, engAbbr: "2CH", ukrName: "II Хроніка", chaptersNum: 36 },
  { id: 15, engAbbr: "EZR", ukrName: "Ездра", chaptersNum: 10 },
  { id: 16, engAbbr: "NEH", ukrName: "Неємія", chaptersNum: 13 },
  { id: 17, engAbbr: "EST", ukrName: "Естера", chaptersNum: 10 },
  { id: 18, engAbbr: "JOB", ukrName: "Іов", chaptersNum: 42 },
  { id: 19, engAbbr: "PSA", ukrName: "Псалми", chaptersNum: 150 },
  { id: 20, engAbbr: "PRO", ukrName: "Приповідки", chaptersNum: 31 },
  { id: 21, engAbbr: "ECC", ukrName: "Проповідник", chaptersNum: 12 },
  { id: 22, engAbbr: "SNG", ukrName: "Пісня пісень", chaptersNum: 8 },
  { id: 23, engAbbr: "ISA", ukrName: "Ісая", chaptersNum: 66 },
  { id: 24, engAbbr: "JER", ukrName: "Єремiя", chaptersNum: 52 },
  { id: 25, engAbbr: "LAM", ukrName: "Плач Єремiї", chaptersNum: 5 },
  { id: 26, engAbbr: "EZK", ukrName: "Єзекiїль", chaptersNum: 48 },
  { id: 27, engAbbr: "DAN", ukrName: "Даниїл", chaptersNum: 12 },
  { id: 28, engAbbr: "HOS", ukrName: "Осiя", chaptersNum: 14 },
  { id: 29, engAbbr: "JOL", ukrName: "Йоіл", chaptersNum: 3 },
  { id: 30, engAbbr: "AMO", ukrName: "Амос", chaptersNum: 9 },
  { id: 31, engAbbr: "OBA", ukrName: "Овдiй", chaptersNum: 1 },
  { id: 32, engAbbr: "JON", ukrName: "Йона", chaptersNum: 4 },
  { id: 33, engAbbr: "MIC", ukrName: "Міхей", chaptersNum: 7 },
  { id: 34, engAbbr: "NAM", ukrName: "Наум", chaptersNum: 3 },
  { id: 35, engAbbr: "HAB", ukrName: "Авакум", chaptersNum: 3 },
  { id: 36, engAbbr: "ZEP", ukrName: "Софонiя", chaptersNum: 3 },
  { id: 37, engAbbr: "HAG", ukrName: "Аггей", chaptersNum: 2 },
  { id: 38, engAbbr: "ZEC", ukrName: "Захарiя", chaptersNum: 14 },
  { id: 39, engAbbr: "MAL", ukrName: "Малахія", chaptersNum: 4 },
  { id: 40, engAbbr: "MAT", ukrName: "Матей", chaptersNum: 28 },
  { id: 41, engAbbr: "MRK", ukrName: "Марко", chaptersNum: 16 },
  { id: 42, engAbbr: "LUK", ukrName: "Лука", chaptersNum: 24 },
  { id: 43, engAbbr: "JHN", ukrName: "Йоан", chaptersNum: 21 },
  { id: 44, engAbbr: "ACT", ukrName: "Діяння", chaptersNum: 28 },
  { id: 45, engAbbr: "ROM", ukrName: "До римлян", chaptersNum: 16 },
  { id: 46, engAbbr: "1CO", ukrName: "I до Корінтян", chaptersNum: 16 },
  { id: 47, engAbbr: "2CO", ukrName: "II до Корінтян", chaptersNum: 13 },
  { id: 48, engAbbr: "GAL", ukrName: "До Галатiв", chaptersNum: 6 },
  { id: 49, engAbbr: "EPH", ukrName: "До Ефесян", chaptersNum: 6 },
  { id: 50, engAbbr: "PHP", ukrName: "До Филипʼян", chaptersNum: 4 },
  { id: 51, engAbbr: "COL", ukrName: "До Колосян", chaptersNum: 4 },
  { id: 52, engAbbr: "1TH", ukrName: "I до Солунян", chaptersNum: 5 },
  { id: 53, engAbbr: "2TH", ukrName: "II до Солунян", chaptersNum: 3 },
  { id: 54, engAbbr: "1TI", ukrName: "I до Тимотея", chaptersNum: 6 },
  { id: 55, engAbbr: "2TI", ukrName: "II до Тимотея", chaptersNum: 4 },
  { id: 56, engAbbr: "TIT", ukrName: "До Тита", chaptersNum: 3 },
  { id: 57, engAbbr: "PHM", ukrName: "До Филимона", chaptersNum: 1 },
  { id: 58, engAbbr: "HEB", ukrName: "До євреїв", chaptersNum: 13 },
  { id: 59, engAbbr: "JAS", ukrName: "Якова", chaptersNum: 5 },
  { id: 60, engAbbr: "1PE", ukrName: "I Послання Петра", chaptersNum: 5 },
  { id: 61, engAbbr: "2PE", ukrName: "II Послання Петра", chaptersNum: 3 },
  { id: 62, engAbbr: "1JN", ukrName: "I Послання Йоана", chaptersNum: 5 },
  { id: 63, engAbbr: "2JN", ukrName: "II Послання Йоана", chaptersNum: 1 },
  { id: 64, engAbbr: "3JN", ukrName: "III Послання Йоана", chaptersNum: 1 },
  { id: 65, engAbbr: "JUD", ukrName: "Послання Юди", chaptersNum: 1 },
  { id: 66, engAbbr: "REV", ukrName: "Обʼявлення", chaptersNum: 22 },
];

export const HornerData = {
  Pentateuch: [1, 2, 3, 4, 5],
  History: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
  Wisdom: [18, 21, 22],
  Psalms: [19],
  Proverbs: [20],
  Prophets: [
    23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
  ],
  Gospels: [40, 41, 42, 43],
  Acts: [44],
  Pauline: [45, 46, 47, 48, 49, 50, 51, 58],
  Epistles: [52, 53, 54, 55, 56, 57, 59, 60, 61, 62, 63, 64, 65, 66],
};
